[package]
name = "carbon_nanotube"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.10.0"
nalgebra = "0.34.1"
chrono = "0.4"
csv = "1.3"
log = "0.4"
env_logger = "0.11"
approx = "0.5.1"
rand_distr = "0.6.0"

